### ISSUE TITLE
DOM "manually" generated instead of using Angular features

### ISSUE THREAD

**Issue by alcfeoh** [Giratin/ng-weather#2]
The code for the dropdown is very much "jquery-like" and not really using Angular features that would simplify things a lot:

```
  createCountryInput(id, strLength, country) {
        const element = this.renderer.createElement('div');
        this.renderer.setProperty(element, 'id', id);
        element.innerHTML = `<strong>${country.substr(0, strLength)}</strong>`;
        element.innerHTML += country.substr(strLength);
        element.innerHTML += `<input type='hidden' name='${id}' value='${country}' />`;

        this.renderer.listen(element, 'click', (e: PointerEvent) => {
            let item = this.myInputautocomplete.nativeElement.querySelector(`[name="${e.target["id"]}"]`) as HTMLInputElement;
            this.onSelect.emit({ country: item.value, id: e.target["id"] });
            this.countrySearch = item.value;
            this.clearList();
        })
        this.renderer.appendChild(this.myInputautocomplete.nativeElement, element);
    }
```

I'd like to see this done in the HTML template of the component rather than by manipulating the DOM "manually", which is usually not a great practice when using Angular.
Typically, the code above is generating a component HTML template from Typescript, when it should really be done in a template itself using directives and such.

**Comment by Giratin** [comment]
Hello, 
I've changed the autocomplete country filtering list without manipulating the DOM anymore
